[package]
name = "coldshot"
version = "0.4.0"
description = "Fast screenshot capture, annotation and sharing"
authors = ["Rim"]
edition = "2021"

[lib]
name = "coldshot_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-global-shortcut = "2"
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
xcap = "0.6"
image = "0.25"
base64 = "0.22"
chrono = "0.4"

[target.'cfg(windows)'.dependencies]
arboard = "3"
reqwest = { version = "0.13", default-features = false, features = ["native-tls"] }

[target.'cfg(target_os = "linux")'.dependencies]
arboard = { version = "3", features = ["wayland-data-control"] }
reqwest = { version = "0.13", default-features = false, features = ["rustls"] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
